### PR TITLE
Removing Builds

### PR DESCRIPTION
**Pull request by jpdevries**
It takes a while to check this project out in git because all the transport packages within the version control. 
This PR suggests a workflow of tagging releases with `git tag` and then uploading the transport package to the associated tag.

Closes craftsmancoding/assetmanager#63

### CODE REVIEW

**Comment by fireproofsocks** [comment]
Hmm... maybe a better option would be a dedicated "builds" branch, since the tagging of a commit would follow slightly different behavior in traditional composer packages.  The only reason those builds are there in the first place was because of repeated problems uploading packages to MODX's package repo...

**Comment by jpdevries** [comment]
I can't think of any reason for zips to be under version control...




That's what tags are for and files can be attached to tagged releases. 




For example notice the tranport zip is attached to this release:


https://github.com/modmore/CodeMirror/releases/tag/2.3.0-dev




—

**Comment by fireproofsocks** [comment]
Again: the reason they were there is so people could download the latest version when uploading the zips to the MODX repo was failing for unknown reasons.  Granted, that doesn't belong under version control, but it makes sense to keep related files under the same roof.

**Comment by fireproofsocks** [comment]
I see what you mean -- yeah, that's a cleaner way.

**Comment by jpdevries** [comment]
If they are on Github, it's pretty much under the same roof. For example, could have a releases list of links to tags in the README. 



—

**Pull request merged**
